services:
  db:
    image: postgres:16.1
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
      POSTGRES_DB: ars_amoris_design_dev
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  webapp:
    build: 
      context: .
    volumes:
      - app-images:/app/Images
    environment:
      DATABASE_URL: Host=db;Port=5432;Database=ars_amoris_design_dev;Username=postgres;Password=postgrespass
      TOKEN__SECRET: EZn9KTHFCRQYJLhp3BxDdXH47bxFfyKM
    ports:
      - "5000:80"
    depends_on:
      - db
  # trenutno nije potreban pgadmin
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: email@test.com
  #     PGADMIN_DEFAULT_PASSWORD: pgadmin_password
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - db
volumes:
  app-images: